version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "imagedefinitions.json"
        LoadBalancerInfo:
          ContainerName: "canary-container"
          ContainerPort: 80
