version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: canary-demo
    LAST_IMAGE_PARAM: /canary-demo/last-successful-image-tag
  exported-variables:
    - DEPLOY_ACTION
    - CANARY_PERCENT
    - CANARY_DURATION_MINUTES
    - IMAGE_TAG
    - SKIP_BUILD

phases:
  pre_build:
    commands:
      - echo Reading commit message
      - COMMIT_MSG=$(echo "$CODEBUILD_SOURCE_VERSION" | cut -d':' -f2-)
      - echo "$COMMIT_MSG"

      - export DEPLOY_ACTION=NONE
      - export CANARY_PERCENT=0
      - export CANARY_DURATION_MINUTES=0
      - export SKIP_BUILD=false

      - if echo "$COMMIT_MSG" | grep -q skip-build; then export SKIP_BUILD=true; fi

      - |
        if echo "$COMMIT_MSG" | grep -q "^deploy:canary"; then
          export DEPLOY_ACTION=CANARY
          export CANARY_PERCENT=$(echo "$COMMIT_MSG" | grep -oE '[0-9]+' | head -n 1)
          RAW_DURATION=$(echo "$COMMIT_MSG" | grep -oE '[0-9]+[mh]' | head -n 1)
          if echo "$RAW_DURATION" | grep -q m; then
            export CANARY_DURATION_MINUTES=${RAW_DURATION%m}
          elif echo "$RAW_DURATION" | grep -q h; then
            export CANARY_DURATION_MINUTES=$((${RAW_DURATION%h} * 60))
          fi
        elif echo "$COMMIT_MSG" | grep -q "^deploy:stable"; then
          export DEPLOY_ACTION=STABLE
        elif echo "$COMMIT_MSG" | grep -q "^deploy:promote"; then
          export DEPLOY_ACTION=PROMOTE
        elif echo "$COMMIT_MSG" | grep -q "^deploy:rollback"; then
          export DEPLOY_ACTION=ROLLBACK
        fi

      - echo DEPLOY_ACTION=$DEPLOY_ACTION
      - echo SKIP_BUILD=$SKIP_BUILD

      - |
        if [ "$DEPLOY_ACTION" = "CANARY" ]; then
          if [ "$CANARY_PERCENT" -le 0 ] || [ "$CANARY_PERCENT" -ge 100 ]; then exit 1; fi
          if [ "$CANARY_DURATION_MINUTES" -le 0 ]; then exit 1; fi
        fi

      - |
        if [ "$SKIP_BUILD" = "true" ]; then
          export IMAGE_TAG=$(aws ssm get-parameter --name "$LAST_IMAGE_PARAM" --query Parameter.Value --output text)
        else
          export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
        fi

      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Using image $IMAGE_URI

      - if [ "$SKIP_BUILD" != "true" ]; then aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com; fi

  build:
    commands:
      - if [ "$SKIP_BUILD" = "true" ]; then echo Skipping Docker build; else docker build -t $IMAGE_REPO_NAME . && docker tag $IMAGE_REPO_NAME:latest $IMAGE_URI; fi

  post_build:
    commands:
      - if [ "$SKIP_BUILD" = "true" ]; then echo Skipping Docker push; else docker push $IMAGE_URI && aws ssm put-parameter --name "$LAST_IMAGE_PARAM" --value "$IMAGE_TAG" --type String --overwrite; fi
      - printf '[{"name":"canary-container","imageUri":"%s"}]' "$IMAGE_URI" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
